### PR TITLE
video component created

### PR DESCRIPTION
**Pull request by Halil-Kuray**

### CODE REVIEW

**Comment by loleg** [comment]
The job is failing because the page is not properly connected to Tina, according to the docs.

**Comment by loleg** [comment]
Please explain why `TinaTemplate` is replaced with `Template` everywhere in the description of your Pull Request.

**Comment by Halil-Kuray** [comment]
> Please explain why `TinaTemplate` is replaced with `Template` everywhere in the description of your Pull Request.

It's deprecated so I changed it.

Screenshot 2023-07-14 at 13 07 13

**Comment by loleg** [comment]
Let's merge and see if we can fix this using Tina's tool.

**Pull request merged**
